### ISSUE TITLE
Null pointer for on resume

### ISSUE THREAD

**Issue by Rivaz93** [nisrulz/qreader#26]
I got Null pointer exception sometimes
`Process: com.sparktech.wowcherryscanner, PID: 18639
                                                                                java.lang.IllegalArgumentException: Null image data supplied.
                                                                                    at com.google.android.gms.vision.Frame$Builder.setImageData(Unknown Source)
                                                                                    at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
                                                                                    at java.lang.Thread.run(Thread.java:818)`

**Comment by nisrulz** [comment]
@Rivaz93 any updates as per the latest version? Let me know if its appropriate to close this issue.

**Comment by nisrulz** [comment]
Closing as issue is outdated. Please open a new issue if the issue still persists.
