### ISSUE TITLE
 Fail to connect to camera service

### ISSUE THREAD

**Issue by dineshvadivel** [nisrulz/qreader#4]
Fail to connect to camera service
I have two apps which is using QReader, if one of the app is running in background, i have to kill that first app in order to open my second app.
otherwise i am getting  Fail to connect to camera service. 
> E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.RuntimeException: Fail to connect to camera service
                                                                                 at android.hardware.Camera.native_setup(Native Method)
                                                                                 at android.hardware.Camera.<init>(Camera.java:413)
                                                                                 at android.hardware.Camera.open(Camera.java:366)
                                                                                 at com.google.android.gms.vision.CameraSource.zzIb(Unknown Source)
                                                                                 at com.google.android.gms.vision.CameraSource.start(Unknown Source)
                                                                                 at github.nisrulz.qreader.QREader.startCameraView(QREader.java:127)
                                                                                 at github.nisrulz.qreader.QREader.access$100(QREader.java:35)
                                                                                 at github.nisrulz.qreader.QREader$1.surfaceCreated(QREader.java:92)
                                                                                 at android.view.SurfaceView.updateWindow(SurfaceView.java:610)
                                                                                 at android.view.SurfaceView.access$000(SurfaceView.java:93)
                                                                                 at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:182)
                                                                                 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:864)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2142)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:561)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
                                                                                 at android.os.Handler.handleCallback(Handler.java:730)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

Also application gets crashed when we get into the activity again (the activity which is initiating  the QR start service)

**Comment by nisrulz** [comment]
@dineshvadivel that I am guessing is because the camera is not being releases implicitly , which is referenced in this issue #3 . I will be updating my codebase tonight with this functionality but need to test and verify everything before I do.

**Comment by nisrulz** [comment]
fixed in https://github.com/nisrulz/qreader/issues/3
