### ISSUE TITLE
Fail To connect to camera service

### ISSUE THREAD

**Issue by malti4** [nisrulz/qreader#46]
Th scanner is working awesome in api level >21.But it shows error "Fail TO Connect to camera service" with api level<21.Kindly help

**Comment by nisrulz** [comment]
@malti4 please share some log information such as LogCat output, device configurations and steps to reproduce this issue.

Thank you.

**Comment by malti4** [comment]
Hello Sir,
In the log, it shows fail to connect to the camera .And the device has lollipop os .If u run it in lollipop device it will show this error

**Comment by jcacosta25** [comment]
i have the same error this is the log 

`java.lang.RuntimeException: Fail to connect to camera service
                                                                      at android.hardware.Camera.<init>(Camera.java:715)
                                                                      at android.hardware.Camera.open(Camera.java:511)
                                                                      at com.google.android.gms.vision.CameraSource.zzbig(Unknown Source)
                                                                      at com.google.android.gms.vision.CameraSource.start(Unknown Source)
                                                                      at github.nisrulz.qreader.QREader.startCameraView(QREader.java:221)
                                                                      at github.nisrulz.qreader.QREader.access$400(QREader.java:40)
                                                                      at github.nisrulz.qreader.QREader$1.surfaceCreated(QREader.java:68)
                                                                      at android.view.SurfaceView.updateWindow(SurfaceView.java:632)
                                                                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:162)
                                                                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2238)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6451)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:943)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:755)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:690)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:929)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by nisrulz** [comment]
@jcacosta25 @malti4 Can any one of you confirm that this issue still exists as per the latest version?

**Comment by nisrulz** [comment]
Closing as issue is outdated. Please open a new issue if the issue still persists.
