### ISSUE TITLE
RuntimeException: Fail to connect to camera service

### ISSUE THREAD

**Issue by sm-tester** [nisrulz/qreader#50]
Hi I'm receiving this a crash bug from play store on Samsung device:

`java.lang.RuntimeException: Fail to connect to camera service
	at android.hardware.Camera.native_setup(Native Method)
	at android.hardware.Camera.&lt;init&gt;(Camera.java:419)
	at android.hardware.Camera.open(Camera.java:371)
	at com.google.android.gms.vision.CameraSource.zzbjo(Unknown Source)
	at com.google.android.gms.vision.CameraSource.start(Unknown Source)
	at github.nisrulz.qreader.QREader.startCameraView(QREader.java:221)
	at github.nisrulz.qreader.QREader.access$400(QREader.java:40)
	at github.nisrulz.qreader.QREader$1.surfaceCreated(QREader.java:68)
	at android.view.SurfaceView.updateWindow(SurfaceView.java:586)
	at android.view.SurfaceView.access$000(SurfaceView.java:88)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:891)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2145)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1239)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6396)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
	at android.view.Choreographer.doFrame(Choreographer.java:583)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5511)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)`

About using library version and device details:

![screen shot 2018-01-14 at 1 20 52 pm](https://user-images.githubusercontent.com/3168694/34914080-da6a2c42-f92d-11e7-8601-6b245162429e.png)

I'm using latest 2.1.1 version library.

Device:
  name: samsung SM-G355H
    OS  : Android 4.4.2

**Comment by nisrulz** [comment]
Closing as issue is outdated. Please open a new issue if the issue still persists.
