### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by sengsiva** [nisrulz/qreader#6]
Exception thrown from receiver.
                                                                                java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                                    at android.os.Handler.<init>(Handler.java:200)
                                                                                    at android.os.Handler.<init>(Handler.java:114)
                                                                                    at android.widget.Toast$TN.<init>(Toast.java:344)
                                                                                    at android.widget.Toast.<init>(Toast.java:100)
                                                                                    at android.widget.Toast.makeText(Toast.java:258)
                                                                                    at com.reasei.hotelmanagementsystem.QRScannerActivity$1.onDetected(QRScannerActivity.java:28)
                                                                                    at github.nisrulz.qreader.QREader$2.receiveDetections(QREader.java:115)
                                                                                    at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
                                                                                    at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
                                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by nisrulz** [comment]
Hi @sengsiva, can you share the code section where this occurred. From what I can guess is that you need to run your code on the UI thread since the results re delivered on a different thread.
Please check the sample app / checkout the readme to see a working model.

**Comment by nisrulz** [comment]
@sengsiva There has been a few bug fixes in the library code, please try the latest version of the library to see that its working for you now and close this issue if it does.

**Comment by nisrulz** [comment]
Closing as no response and also it can be solved by using a Handler.
